Repository tlaplus/tlaplus, pull requests merged in 2024-04, with the labels that each got.

#900 Parallelize PR CI workflow
  .github/workflows/pr.yml
Labels: DevEnvironment

#902 Parallelize unit tests
  .github/scripts/parse-unit-test-output.py
  .github/workflows/pr.yml
  tlatools/org.lamport.tlatools/customBuild.xml
  tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/ModelCheckerTestCase.java
  tlatools/org.lamport.tlatools/test/tlc2/tool/simulation/SimulationWorkerTest.java
  tlatools/org.lamport.tlatools/test/tlc2/tool/simulation/SimulatorTest.java
Labels: enhancement, refactoring, DevEnvironment

#876 Run JavaCC at build to generate TLA+ parser files
  .github/workflows/pr.yml
  tlatools/org.lamport.tlatools/customBuild.xml
  tlatools/org.lamport.tlatools/lib/javacc-4.0.jar
Labels: enhancement, DevEnvironment

#896 Add unicode support to SANY
  .github/workflows/pr.yml
  tlatools/org.lamport.tlatools/customBuild.xml
  tlatools/org.lamport.tlatools/javacc/tla+.jj
  tlatools/org.lamport.tlatools/src/tla2sany/configuration/ConfigConstants.java
  tlatools/org.lamport.tlatools/src/tla2sany/modanalyzer/ParseUnit.java
  tlatools/org.lamport.tlatools/src/tla2sany/parser/BracketStack.java
  tlatools/org.lamport.tlatools/src/tla2sany/parser/ParseException.java
  tlatools/org.lamport.tlatools/src/tla2sany/parser/SimpleCharStream.java
  tlatools/org.lamport.tlatools/src/tla2sany/parser/TLAplusParser.java
  tlatools/org.lamport.tlatools/src/tla2sany/parser/TLAplusParserConstants.java
  tlatools/org.lamport.tlatools/src/tla2sany/parser/TLAplusParserTokenManager.java
  tlatools/org.lamport.tlatools/src/tla2sany/parser/Token.java
  tlatools/org.lamport.tlatools/src/tla2sany/parser/TokenMgrError.java
  tlatools/org.lamport.tlatools/src/tla2sany/semantic/BuiltInLevel.java
  tlatools/org.lamport.tlatools/src/tla2sany/semantic/Generator.java
  tlatools/org.lamport.tlatools/test/tla2sany/AstNode.java
  tlatools/org.lamport.tlatools/test/tla2sany/ParseCorpusTest.java
  tlatools/org.lamport.tlatools/test/tla2sany/SanyTranslator.java
  tlatools/org.lamport.tlatools/test/tla2sany/corpus/unicode/case-unicode.txt
  tlatools/org.lamport.tlatools/test/tla2sany/corpus/unicode/conjlist-unicode.txt
  tlatools/org.lamport.tlatools/test/tla2sany/corpus/unicode/disjlist-unicode.txt
  tlatools/org.lamport.tlatools/test/tla2sany/corpus/unicode/functions-unicode.txt
  tlatools/org.lamport.tlatools/test/tla2sany/corpus/unicode/operators-unicode.txt
  tlatools/org.lamport.tlatools/test/tla2sany/corpus/unicode/quantification-unicode.txt
  tlatools/org.lamport.tlatools/test/tla2sany/corpus/unicode/sets-unicode.txt
  tlatools/org.lamport.tlatools/test/tla2sany/corpus/unicode/string-unicode.txt
  tlatools/org.lamport.tlatools/test/tla2sany/corpus/unicode/tuples-unicode.txt
Labels: enhancement, Tools, Unicode, SANY

#908 'constrained' states not added to e.g. dot output if TLC runs under TLA+
  tlatools/org.lamport.tlatools/src/tlc2/tool/impl/DebugTool.java
Labels: bug, Tools

#920 Use Java 11 but not specific version in CI
  .github/workflows/main.yml
  .github/workflows/perf.yml
  .github/workflows/pr.yml
Labels: DevEnvironment
