Repository tlaplus/tlaplus, pull requests merged in 2024-07, with the labels that each got.

#978 Increment translator's version number.
  tlatools/org.lamport.tlatools/src/pcal/PcalParams.java
Labels: PlusCal

#980 Fixes unreachable branch in Simulator#printBehavior
  tlatools/org.lamport.tlatools/src/tlc2/tool/Simulator.java
  tlatools/org.lamport.tlatools/test/tlc2/tool/SimulatorTest.java
Labels: bug, Tools

#977 Locate the the "StandardModules" folder more reliably
  tlatools/org.lamport.tlatools/src/util/SimpleFilenameToStream.java
Labels: enhancement

#988 Add note about Eclipse interference with Ant CLI build
  DEVELOPING.md
Labels: enhancement, DevEnvironment
